Test type check working for args and ret vals
software-mansion-labs/cairo pull request #26
Opened 2023-03-03 15:43 UTC by karol-bisztyga

https://github.com/software-mansion/protostar/issues/1552

2023-03-03 15:45 UTC, karol-bisztyga commented
For now, it works only for args and return values, I couldn't find a way to check if the test is marked with `nopanic`

2023-03-06 11:04 UTC, karol-bisztyga commented
I may be wrong about this but I couldn't find how and if the `nopanic` is handled by the cairo1 compiler. I also ran a simple test - I compiled a simple function with and without `nopanic` and the sierra/casm outputs were the same, so maybe it isn't supported yet if there's no info in sierra about it.

2023-03-06 14:12 UTC, MaksymilianDemitraszek requested changes
It is possible to do it under test-collection binding instead of exposing a new binding?

Also remember about writing a test for it in protostar

2023-03-06 14:12 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-python-bindings/src/lib.rs
> +fn typecheck_sierra_tests(test_names: Vec<String>, sierra_contents: &str) -> PyResult<()> {
I think it would be better to do it inside test collection phase instead of exposing a separate binding. If introduces additional overhead and requires program to be parsed twice.

2023-03-07 08:18 UTC, karol-bisztyga commented on crates/cairo-lang-python-bindings/src/lib.rs
> +fn typecheck_sierra_tests(test_names: Vec<String>, sierra_contents: &str) -> PyResult<()> {
[validate tests when collecting](https://github.com/software-mansion-labs/cairo/pull/26/commits/5df04c236eb53e52761cde73790041fcf563e146)

2023-03-07 10:52 UTC, karol-bisztyga commented
I added checking if the test is panicable

2023-03-07 12:32 UTC, MaksymilianDemitraszek approved these changes
LGTM

2023-03-07 13:05 UTC, merged