Handle print in protostar
software-mansion-labs/cairo pull request #65
Opened 2023-04-21 08:53 UTC by karol-bisztyga

2023-04-21 09:08 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    continue
I think zero bytes are reprezented as `b'\x00'` so even if `bt` is zero this if will never execute.

```python
>>> b'\x00' == 0
False
```

2023-04-21 09:13 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    continue
there's a problem with `\x00`, it cannot be included in this code

2023-04-21 09:17 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                            print(e)
I don't think so. Let me explain a bit of the philosophy behind all of this: I wanted to make the string conversion optional here. If it succeeds, then that's cool, if not, it's ok too. If an exception happens during the conversion, then we can inform the user why they didn't get the string representation. Hmm, maybe we could attach additional piece of information on what caused the problem, something like: `print('string conversion failed: ' + str(e))`

2023-04-21 09:19 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                            print(e)
And as for your comment specifically: I think the broader the better here, as the str conversion is optional, we don't want to break the flow when it fails. I think we should use `BaseException`.

2023-04-21 09:25 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    continue
you get `ValueError: source code string cannot contain null bytes`

2023-04-21 09:33 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    continue
Perhaps we could do some conversion to/from bytes in the condition check then. Because from what I understand, this does nothing currently.

2023-04-21 09:35 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                            print(e)
I understand your motivation. If we have to, I'd stick to `Exception` instead of `BaseException`. I'm afraid that catching every possible exception like that could lead to some hard to resolve bugs in the debug print in the future, but maybe there's no risk of that.

2023-04-21 10:10 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    continue
what do you mean it does nothing?

2023-04-21 10:11 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                            print(e)
that's not the case because we specifically wrap this part of code that does the conversion with `try ... except`, nothing else, so the rest of the code behaves normally.

2023-04-21 10:12 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    non_zero_byte_encountered = True
discussion in https://github.com/software-mansion-labs/cairo/pull/65#discussion_r1173532464

2023-04-21 10:27 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                            print(e)
Okay let's keep it like this

2023-04-21 10:36 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                                    continue
My bad, I thought that iterating over byte object you still get bytes inside the loop instead of ints.

2023-04-21 10:37 UTC, cptartur approved these changes

2023-04-21 10:37 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        except BaseException as e:
Still not sure about using `BaseException` here instead of just `Exception`. But if you think it should be like this, we can keep it.

2023-04-21 11:48 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        except BaseException as e:
discussed offline

2023-04-24 08:49 UTC, piotmag769 approved these changes

2023-04-24 09:17 UTC, piotmag769 commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        original_value_msg = 'original value: [' + str(value) + ']'
```suggestion
                        original_value_msg = 'original value: [' + hex(value) + ']'
```

This way we can differentiate bytes visually without converting it to hex by hand. For example printing 'hello' this way results in:

`"original value: [0x68656c6c6f] converted to a string: [hello]"`

Now a user would be able to see a byte corresponding to every character (h = 0x68, e = 0x65 etc.).|
Otherwise we get int('0x68656c6c6f', 16) = 448378203247 - not very user friendly imo.

Counterargument: in cairo0 `serialize_word` doesn't convert to hex.

WDYT?

2023-04-24 09:34 UTC, piotmag769 commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        original_value_msg = 'original value: [' + str(value) + ']'
cc @MaksymilianDemitraszek @Arcticae @cptartur

2023-04-24 11:08 UTC, Arcticae commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        original_value_msg = 'original value: [' + str(value) + ']'
I would leave decimal

2023-04-24 14:25 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        original_value_msg = 'original value: [' + str(value) + ']'
I think both hex and decimal values are equally not very useful. Don't think many users will be handling their errors based on these raw values - we can use any representation imo.

2023-04-25 06:32 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        original_value_msg = 'original value: [' + str(value) + ']'
> I think both hex and decimal values are equally not very useful. Don't think many users will be handling their errors based on these raw values - we can use any representation imo.

It's not only about handling exceptions but about printing out anything that you may need.

I'd lean towards using the decimal format. This is because, if we use print for debugging, it's easier to read decimal values.

> Now a user would be able to see a byte corresponding to every character (h = 0x68, e = 0x65 etc.).
Otherwise we get int('0x68656c6c6f', 16) = 448378203247 - not very user friendly imo.

That's cool but please note that you're going to have this value's string representation anyways, I don't see how the hex form could be useful. Do you have any particular case for that?

For me, there are several cases:
- you want to print a number - decimal is better than hex
- you want to print a boolean - doesn't matter that much
- you want to print a string - there's a string representation printed
- you want to print an array/other collection - doesn't change anything as each element's going to be printed separately

2023-04-25 07:03 UTC, MaksymilianDemitraszek requested changes
If we are implementing such heavy logic can we make it a hint local in protostar codebase? It will be much easier to iterate on it. Additionally, it will be much more testable and It would be nice to have unit tests for this complex printing logic

2023-04-25 08:35 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                        except BaseException as e:
The point here is, we want to catch the most generic error possible. This is because I treat printing the string representation as something optional. If that fails for any reason, we want to still print the original value instead of breaking the flow.

2023-04-25 08:36 UTC, karol-bisztyga commented
> If we are implementing such heavy logic can we make it a hint local in protostar codebase? It will be much easier to iterate on it. Additionally, it will be much more testable and It would be nice to have unit tests for this complex printing logic

Sure, I'm cool with this, we were considering doing so so I always considered it as an option.

2023-04-26 09:55 UTC, cptartur commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                ",
Could this logic be handled in protostar? So that we would only pass data from memory and handle printing and parsing in protostar?

2023-04-26 09:55 UTC, cptartur commented on crates/cairo-lang-sierra-gas/src/cheatcodes_libfunc_cost_base.rs
> +        CheatcodesConcreteLibFunc::Print(_) => vec![ops.steps(1)],
Does it use any steps at all? We have ap change 0 so shouldn't this also be 0?

2023-04-26 09:55 UTC, cptartur commented on crates/cairo-lang-sierra-to-casm/src/invocations/cheatcodes/print.rs
> +    };
I think `;` at the end of this is not needed? At least that's what intellij suggests.

2023-04-26 09:55 UTC, cptartur commented on crates/cairo-lang-sierra-to-casm/src/invocations/cheatcodes/print.rs
> +    };
Same here

2023-04-26 09:55 UTC, cptartur commented on crates/cairo-lang-sierra/src/extensions/modules/cheatcodes.rs
> +        // (Span<StringLimb>, len), or something like that.
Should we include this TODO?

2023-04-26 09:55 UTC, cptartur commented on crates/cairo-lang-sierra/src/extensions/modules/cheatcodes.rs
> +    }
This is much different from other cheatcodes in this file. Is it on purpose?

2023-04-26 12:50 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                ",
Hmm, right, we probably should move this to protostar, especially since we'll be able to use the existing function for converting the data to a string. At first, I wanted to avoid adding another hint local but I think it's going to be beneficial after all.

2023-04-26 12:54 UTC, karol-bisztyga commented on crates/cairo-lang-sierra-gas/src/cheatcodes_libfunc_cost_base.rs
> +        CheatcodesConcreteLibFunc::Print(_) => vec![ops.steps(1)],
The cost has to be `1`, otherwise there are errors all over the place. I ain't sure how this works exactly though.

2023-04-26 12:54 UTC, karol-bisztyga commented on crates/cairo-lang-sierra-to-casm/src/invocations/cheatcodes/print.rs
> +    };
right

2023-04-26 12:56 UTC, karol-bisztyga commented on crates/cairo-lang-sierra/src/extensions/modules/cheatcodes.rs
> +        // (Span<StringLimb>, len), or something like that.
This is basically copied from `cairo/crates/cairo-lang-sierra/src/extensions/modules/debug.rs`.
I don't think we should do anything with it.

2023-04-26 14:14 UTC, cptartur commented on crates/cairo-lang-sierra-gas/src/cheatcodes_libfunc_cost_base.rs
> +        CheatcodesConcreteLibFunc::Print(_) => vec![ops.steps(1)],
I'm not sure either. We can keep it as 1 if 0 causes errors.

2023-04-26 14:14 UTC, cptartur commented on crates/cairo-lang-sierra/src/extensions/modules/cheatcodes.rs
> +        // (Span<StringLimb>, len), or something like that.
Hmm, if you think thats okay, we can keep it.

2023-04-26 14:29 UTC, karol-bisztyga commented on crates/cairo-lang-casm/src/hints/mod.rs
> +                ",
[use protostar's hint local](https://github.com/software-mansion-labs/cairo/pull/65/commits/d39cfd1aef5b9ebf384e4771270be639ce1f1de5)

2023-04-27 11:19 UTC, MaksymilianDemitraszek approved these changes

2023-04-27 11:32 UTC, merged