Declare rust
software-mansion-labs/cairo pull request #88
Opened 2023-06-12 08:13 UTC by karol-bisztyga

2023-06-13 15:04 UTC, MaksymilianDemitraszek approved these changes

2023-06-13 15:23 UTC, MaksymilianDemitraszek requested changes

2023-06-13 15:23 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +                CompilerConfig { ..CompilerConfig::default() },
We should't compile it here, we should use artifact produced by scarb with build.

2023-06-14 10:08 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/lib.rs
> +}
I am not sure, config is something user provides and user does not provide corelib path.

2023-06-14 14:15 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let paths = std::fs::read_dir("./target/dev").unwrap();
the problem is scarb leaves files in the filesystem.

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-compiler/src/db.rs
> +
Unsure about this addition. I've considered the same in #84 but we've eventually decided that it would be better to limit changes in the compiler to only necessary ones, that's why this wasn't included.

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-compiler/src/db.rs
> +    pub fn set_corelib_path(&mut self, corelib_path: PathBuf) -> &mut Self {
Is this used anywhere at all? I see that `collect_tests` still just mutates underlying `db` manually.

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            SnapboxCommand::new("scarb")
I'm unsure if using snapbox here, it's generally designed to be used for testing programs. 

We should use std::process::Command here instead https://doc.rust-lang.org/std/process/struct.Command.html

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +                let path_str = path.unwrap().path().to_str().unwrap().to_string();
Maybe provide some errors here instead of unwrap?

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_class = BlockifierContractClass::V1(contract_class);
I'm unsure calling scarb as subprocess and building it here

cc @MaksymilianDemitraszek

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            deploy_account_tx.max_fee = Fee(0);
Will this work with max_fee set to 0?

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let bal = blockifier_state.state.get_fee_token_balance(&block_context, &contract_address2);
This seems unused

2023-06-14 14:40 UTC, cptartur commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_address2 = ContractAddress::try_from(arg_starkfelt).unwrap();
This could use a better name. It's not really obvious what this address is and why we need if we already have `contract_address`.

2023-06-15 06:48 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/lib.rs
> +}
has been removed due to building with scarb

2023-06-15 06:52 UTC, karol-bisztyga commented on crates/cairo-lang-compiler/src/db.rs
> +
has been removed

2023-06-15 06:52 UTC, karol-bisztyga commented on crates/cairo-lang-compiler/src/db.rs
> +    pub fn set_corelib_path(&mut self, corelib_path: PathBuf) -> &mut Self {
its removed

2023-06-15 06:58 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +                let path_str = path.unwrap().path().to_str().unwrap().to_string();
you're right, although at that time I was unsure whether this is a good approach at all. If we decide to go this way, I'll replace all unwraps

2023-06-15 07:02 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_class = BlockifierContractClass::V1(contract_class);
> I'm unsure calling scarb as subprocess and building it here

Ok, so the problem here is that we want to build on-demand. If we have some tests, we don't want to build everything right away, right? What if there's no `declare` in these tests? Then it would be a redundant build. Therefore I think we should build inside of declare.

> I think we should move it to our test runner (and just call it before collecting tests for now) to limit modifications made to the compiler as we will get rid of it eventually

The code for cheat codes that is here will be moved to our test runner once we switch to [this solution](https://github.com/starkware-libs/cairo/pull/3283)

2023-06-15 07:04 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            deploy_account_tx.max_fee = Fee(0);
I do not understand the question. It is set to 0 and it works, did you mean something else?

2023-06-15 07:09 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let bal = blockifier_state.state.get_fee_token_balance(&block_context, &contract_address2);
right, weird rust didn't throw a warning for this.

2023-06-15 07:12 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_address2 = ContractAddress::try_from(arg_starkfelt).unwrap();
its unused anyway so should be removed

2023-06-15 07:12 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_address2 = ContractAddress::try_from(arg_starkfelt).unwrap();
[fdbck](https://github.com/software-mansion-labs/cairo/pull/88/commits/8196246cec4e584f3925795765313893309be337)

2023-06-15 07:17 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +                let path_str = path.unwrap().path().to_str().unwrap().to_string();
[remove unweraps](https://github.com/software-mansion-labs/cairo/pull/88/commits/cbacb72909c4a604024228f0de680ffefa0e539c)

2023-06-15 07:18 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            SnapboxCommand::new("scarb")
Do you have any sources on why we should switch to `std::process::Command`? What are the differences and which of them make a difference in this matter?

2023-06-15 07:26 UTC, MaksymilianDemitraszek requested changes

2023-06-15 07:26 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let bal = blockifier_state.state.get_fee_token_balance(&block_context, &contract_address2);
I believe this is copied from blockifier testing code, it probably should be removed though

2023-06-15 07:26 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_class = BlockifierContractClass::V1(contract_class);
Not sure if I agree here, there are some benefits of compiling on demand but contract pre-compilation at the beginning is in my opion a better solution. Benefits I see:

1. We compile all of the contracts here, not only the single one required.
2. In 99% of testing setups contracts will be tested, and each of them will be tested multiple times, thus precompilation will result in performance gains for the most common case and this is the one we should optimize.
3. It will better fit the case if we decide to contract auto pre-declaration (before test execution) in the future.

---

Also you match contract names based on compiled contract name, those names format is not guaranteed by scarb. We should use `contract name -> path` map produced by scarb 0.4 instead, it is produced when `build` command is run. @maciektr can provide more info on that.

2023-06-15 07:26 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/lib.rs
> +    pub corelib_path: String,
Why we need to pass it here?

2023-06-15 08:31 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +        ProtostarHint::Deploy {
I mentioned on slack that we move this code to `StarknetHint::SystemCall` instead so we could use all of good stuff provided by dispatchers. We can merge this as it is for now just letting you know.

2023-06-15 11:26 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +        ProtostarHint::Deploy {
sure

2023-06-15 11:26 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/lib.rs
> +    pub corelib_path: String,
t b rmvd

2023-06-15 12:51 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_class = BlockifierContractClass::V1(contract_class);
@MaksymilianDemitraszek makes sense

2023-06-15 13:15 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/lib.rs
> +    pub corelib_path: String,
[remove redundant struct](https://github.com/software-mansion-labs/cairo/pull/88/commits/6352ee0818d28db2a6fc6a7049b4b9ce28c9fbf9)

2023-06-15 13:27 UTC, piotmag769 commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let paths = std::fs::read_dir("./target/dev").unwrap();
Is it really a problem? I think it's fine for the files to stay, they don't do any harm

2023-06-15 13:32 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +                as_cairo_short_string(&contract_value).expect("conversion to short string failed");
We should either do these labels or not, I don't think doing this in one place and skipping in the rest is a good idea. If you feel like we should add them, please post an issue, however from what I've seen around the codebase, it is not a common practice so I'd not do that at all.

2023-06-16 07:27 UTC, karol-bisztyga commented on crates/cairo-lang-protostar/src/test_collector/mod.rs
> +    linked_libraries: &Option<Vec<LinkedLibrary>>,
[fdbck](https://github.com/software-mansion-labs/cairo/pull/88/commits/db9e03fa740f11f5a289b10b253b3dacf1c1799e)

2023-06-16 07:27 UTC, karol-bisztyga commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            let contract_class = BlockifierContractClass::V1(contract_class);
[prebuild contracts](https://github.com/software-mansion-labs/cairo/pull/88/commits/39f4b2da6deab872849a3c5fa71801c9664d9315)

2023-06-16 08:34 UTC, MaksymilianDemitraszek approved these changes
Can we create a task for using scarb map artifact before merging?

2023-06-16 08:35 UTC, karol-bisztyga commented
https://github.com/software-mansion/protostar/issues/2081

2023-06-16 08:51 UTC, MaksymilianDemitraszek commented on crates/cairo-lang-runner/src/casm_run/mod.rs
> +            SnapboxCommand::new("scarb")
I generaly agree here that it seems inappropriate, it supports a lot of testing features which may introduce some additonal overhead or modify the behaviour. Not sure though if I can give you an exact example what might be a problem.

2023-06-16 09:09 UTC, merged